version: '3'
services:
  db:
    image: mysql:latest
    container_name: energizou_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: energizou_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: energizou_app
    ports:
      - "3333:3333"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 1234
      DB_NAME: energizou_db
    depends_on:
      - db
    command: npm run dev

volumes:
  mysql-data:
